[package]
name = "git-repository"
repository = "https://github.com/Byron/gitoxide"
description = "Abstractions for git repositories"
license = "MIT/Apache-2.0"
version = "0.6.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
include = ["src/**/*", "src/assets/**"]

[lib]
doctest = false
test = true

[features]
default = ["max-performance", "one-stop-shop"]
max-performance = ["git-features/zlib-ng-compat", "git-features/fast-sha1"]
serde1 = ["git-pack/serde1", "git-object/serde1"]
one-stop-shop = [
    "git-features",
    "git-features/progress",
    "git-features",
    "git-hash",
    "git-traverse",
    "git-diff",
    "git-object",
    "git-pack/pack-cache-lru-dynamic",
    "git-pack/pack-cache-lru-static",
    "git-protocol"
]


[dependencies]
git-ref = { version = "0.5.0", path = "../git-ref" }
git-odb = { version = "^0.16", path = "../git-odb" }
git-hash = { version = "^0.4.0", path = "../git-hash", optional = true }
git-pack = { version = "^0.2", path = "../git-pack", optional = true }
git-object = { version = "^0.10", path = "../git-object", optional = true }
git-traverse = { version = "^0.3", path = "../git-traverse", optional = true }
git-protocol = { version = "^0.8.0", path = "../git-protocol", optional = true }
git-diff = { version = "^0.4", path = "../git-diff", optional = true }
git-features = { version = "^0.15.0", path = "../git-features", optional = true }

quick-error = "2.0.0"

[dev-dependencies]
git-testtools = { version = "^0.2", path = "../tests/tools" }
