[package]
name = "git-ref"
version = "0.5.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A crate to handle git references"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
include = ["src/**/*"]

[lib]
doctest = false
test = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git-hash = { version = "^0.4.0", path = "../git-hash" }
git-validate = { version = "^0.2.0", path = "../git-validate" }

quick-error = "2.0.0"
bstr = { version = "0.2.13", default-features = false, features = ["std"] }
nom = { version = "6", default-features = false, features = ["alloc"]}

[dev-dependencies]
git-testtools = { version = "^0.2", path = "../tests/tools" }
